apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: wordcount-job
spec:
  resourceSelectors:
    - apiVersion: batch.volcano.sh/v1alpha1
      kind: Job
      name: wordcount-job
  placement:
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided