apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: wordcount-job-cpp
spec:
  resourceSelectors:
    - apiVersion: batch.volcano.sh/v1alpha1
      kind: Job
      name: wordcount-job
  placement:
    clusterAffinity:
      clusterNames:
        - kubernetes-dc1
